### ISSUE TITLE
Can´t connect to new created API because of "wrong" API Key

### ISSUE THREAD

**Issue by ChristianTroll** [Invertee/GDAX-Powershell#10] opened 2020-11-30 11:01 UTC
Hi,
i just startet new with this API and the Powershell extension. First of all, thanks for creating it!
Yesterday i created my API for Coinbase and Pro. Now i want to connect.
Created variables for $ApiKey, $ApiPassphrase and $ApiSecret (values are correct)
Used command: 
$Account = Get-CoinbaseAccounts -APIKey $APIKey -APISecret $APISecret -APIPhrase $APIPassphrase

Result:
Invoke-CoinbaseProRequest : Unauthorized. Invalid API Key
In D:\_GIT\CoinbasePro-Powershell\Functions\Private\Get-CoinbaseAccounts.ps1:17 Zeichen:17
     $response = Invoke-CoinbaseProRequest $api
    CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-CoinbaseProRequest

What do i make wrong?  Any help would be nice.
Thanks

**Comment by ChristianTroll** [comment] 2020-12-05 00:34
Found the problem: For whatever reason need to change row in "Invoke-CoinbaseRequest.ps1" from
$Timestamp = ([math]::Round($Timestamp, 3)).ToString()
to
$Timestamp = ([math]::Round($Timestamp, 0)).ToString()

**Comment by stephenc01** [comment] 2020-12-28 13:41
Hey, I just tested and cannot reproduce this. What PS version are you using? I tested on 7.1

**Comment by Invertee** [comment] 2021-01-18 21:23
Duplicate of #9

**Closed as completed by Invertee** 2021-01-18 21:23 UTC
